management:
  endpoints:
    web:
      exposure:
          include: info, health, bus-refresh, hystrix.stream


feign:
    hystrix:
        enabled: true

server:
  port: ${port:8181}

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest

  zipkin:
    sender:
      type: web
    baseUrl: ${ZIPKIN_URL:http://localhost:9411}
  sleuth:
    sampler:
      probability: 1.0
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE_URL:http://localhost:8761/eureka}
