server:
  port: ${port:8989}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE_URL:http://localhost:8761/eureka}

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest

turbine:
  appConfig: product-service
  cluster-name-expression: "'default'"


management:
  endpoints:
    web:
      exposure:
          include: health, bus-refresh
