management:
  endpoints:
    web:
      exposure:
          include: info, health, bus-refresh, actuator, refresh
          
server:
  port: ${port:5555}

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest
  
  zipkin:
    sender:
      type: web
    baseUrl: ${ZIPKIN_URL:http://localhost:9411}
  sleuth:
    sampler:
      probability: 1.0 

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE_URL:http://localhost:8761/eureka}
      
zuul:
  prefix: /api
